"""
soft_arm_scene.py — SOFA + SoftRobots scene for the fabric pneumatic soft arm.

This file defines a SofaPython3-compatible scene builder function `createScene()`
that SOFA calls on startup.  It can also be used programmatically via
`SoftArmSim` in soft_arm_sim.py.

Physics overview
----------------
The arm body is modelled as a nearly-incompressible hyperelastic solid using
the Finite Element Method (FEM) on a tetrahedral mesh generated by Gmsh
(mesh/generate_mesh.py).

    Body mechanics
        TetrahedronFEMForceField (co-rotational, large deformation)
        Rayleigh damping (α on mass, β on stiffness)

    Pneumatic actuation
        SurfacePressureConstraint × 20 (one per column/level pouch)
        First-order pressure lag applied by the GUI panel or soft_arm_sim.py

    Boundary conditions
        FixedProjectiveConstraint on the base face (mesh tag 2 = mount plate)

    Solver stack (constraint-based)
        FreeMotionAnimationLoop
        GenericConstraintSolver
        SparseLDLSolver  (direct, robust for ~10k DOF problems)
        EulerImplicitSolver (with Rayleigh damping)

Scene graph
-----------
Root
 ├─ RequiredPlugin (SoftRobots, SofaPython3, SofaBaseLinearSolver, …)
 ├─ AnimationLoop (FreeMotionAnimationLoop)
 ├─ ConstraintSolver (GenericConstraintSolver)
 ├─ PressureControls
 │   └─ PressureControlPanel  ← GUI-editable 4 × 5 pressure matrix
 └─ Arm  (Node)
     ├─ EulerImplicitSolver
     ├─ SparseLDLSolver
     ├─ MeshGmshLoader          ← loads soft_arm.msh
     ├─ TetrahedronSetTopologyContainer
     ├─ MechanicalObject        ← DOFs (node positions)
     ├─ TetrahedronFEMForceField
     ├─ UniformMass
     ├─ LinearSolverConstraintCorrection
     ├─ FixedProjectiveConstraint ← base nodes (mount plate)
     ├─ Col{0..3}_..._Lvl{0..4}  (20 independent pouch nodes)
     │   ├─ MeshTopology (triangles from the pouch's physical group)
     │   ├─ MechanicalObject + BarycentricMapping
     │   └─ SurfacePressureConstraint
     └─ Tip  (sub-node)
         ├─ MechanicalObject    ← mapped tip position
         └─ BarycentricMapping  ← maps tip DOF to arm FEM DOFs
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

# arm_config is always importable (pure Python, no SOFA dependency)
from arm_config import ArmConfig
from robot_visual import add_robot_visual


def _load_pouch_surfaces(
    mesh_path: Path, expected_tags: set[int]
) -> dict[int, tuple[list[list[float]], list[list[int]]]]:
    """Read tagged pouch surfaces from an ASCII Gmsh MSH2 mesh.

    SOFA's ``MeshGmshLoader`` loads the complete volume mesh but cannot filter
    it by physical group.  The scene therefore reads the small amount of MSH2
    metadata it needs and builds one local surface topology per pouch.
    """
    node_positions: dict[int, list[float]] = {}
    tagged_triangles: dict[int, list[list[int]]] = {
        tag: [] for tag in expected_tags
    }

    with mesh_path.open(encoding="utf-8") as mesh_file:
        lines = iter(mesh_file)
        for raw_line in lines:
            section = raw_line.strip()
            if section == "$MeshFormat":
                version = next(lines).split()[0]
                if not version.startswith("2."):
                    raise ValueError(
                        f"{mesh_path} uses MSH {version}; regenerate it with "
                        "mesh/generate_mesh.py to produce MSH2 ASCII"
                    )
            elif section == "$Nodes":
                node_count = int(next(lines))
                for _ in range(node_count):
                    fields = next(lines).split()
                    node_positions[int(fields[0])] = [
                        float(fields[1]),
                        float(fields[2]),
                        float(fields[3]),
                    ]
            elif section == "$Elements":
                element_count = int(next(lines))
                for _ in range(element_count):
                    fields = next(lines).split()
                    element_type = int(fields[1])
                    tag_count = int(fields[2])
                    if element_type != 2 or tag_count == 0:
                        continue
                    physical_tag = int(fields[3])
                    if physical_tag in tagged_triangles:
                        first_node = 3 + tag_count
                        tagged_triangles[physical_tag].append(
                            [int(value) for value in fields[first_node:first_node + 3]]
                        )

    missing = [tag for tag, triangles in tagged_triangles.items() if not triangles]
    if missing:
        raise ValueError(f"Mesh is missing pouch physical groups: {missing}")

    surfaces: dict[int, tuple[list[list[float]], list[list[int]]]] = {}
    for tag, triangles in tagged_triangles.items():
        node_ids = list(dict.fromkeys(node for triangle in triangles for node in triangle))
        local_index = {node_id: index for index, node_id in enumerate(node_ids)}
        positions = [node_positions[node_id] for node_id in node_ids]
        local_triangles = [
            [local_index[node_id] for node_id in triangle]
            for triangle in triangles
        ]
        surfaces[tag] = positions, local_triangles

    return surfaces


# ---------------------------------------------------------------------------
# Scene creation entry point — called by SOFA on startup
# ---------------------------------------------------------------------------

def createScene(
    root_node,
    cfg: Optional[ArmConfig] = None,
    enable_pressure_panel: bool = False,
):
    """Build the SOFA scene graph for the soft arm.

    Parameters
    ----------
    root_node : Sofa.Core.Node
        The SOFA root node (provided automatically by `runSofa` or by
        `Sofa.Simulation.init()`).
    cfg : ArmConfig, optional
        Physical parameters.  Defaults to ``ArmConfig()``.
    enable_pressure_panel : bool
        Add the interactive 4 x 5 pressure controller shown by the SOFA GUI.
        The programmatic ``SoftArmSim`` wrapper disables it because that API
        writes the same actuators directly.

    Returns
    -------
    arm_node : Sofa.Core.Node
        The arm sub-node; use it to access DOFs, actuators, and sensors
        from outside the scene.
    """
    if cfg is None:
        cfg = ArmConfig()

    # ── Required plugins (SOFA v26 names) ────────────────────────────────
    root_node.addObject("RequiredPlugin", pluginName=[
        "SoftRobots",                                       # SurfacePressureConstraint
        "Sofa.Component.LinearSolver.Direct",               # SparseLDLSolver
        "Sofa.Component.ODESolver.Backward",                # EulerImplicitSolver
        "Sofa.Component.Constraint.Lagrangian.Correction",  # LinearSolverConstraintCorrection
        "Sofa.Component.Constraint.Lagrangian.Solver",      # BlockGaussSeidelConstraintSolver
        "Sofa.Component.AnimationLoop",                     # FreeMotionAnimationLoop
        "Sofa.Component.SolidMechanics.FEM.Elastic",        # TetrahedronFEMForceField
        "Sofa.Component.Topology.Container.Dynamic",        # TetrahedronSetTopologyContainer
        "Sofa.Component.Topology.Container.Constant",       # MeshTopology
        "Sofa.Component.Mass",                              # UniformMass
        "Sofa.Component.IO.Mesh",                           # MeshGmshLoader
        "Sofa.Component.Constraint.Projective",             # FixedProjectiveConstraint
        "Sofa.Component.Engine.Select",                     # BoxROI
        "Sofa.Component.Mapping.Linear",                    # BarycentricMapping
        "Sofa.GL.Component.Rendering3D",                    # OglModel (visual)
        "Sofa.Component.Setting",                           # BackgroundSetting
        "Sofa.Component.Visual",                            # VisualStyle
        "Sofa.Component.StateContainer",                    # MechanicalObject
    ])

    # ── Global scene settings ─────────────────────────────────────────────
    # The mesh's local +Z axis runs down from the plywood mount to the tip.
    # Gravity therefore acts in +Z for the hanging configuration.
    gravity_z = 9.81 if cfg.hang_down else -9.81
    root_node.gravity = [0.0, 0.0, gravity_z]
    root_node.dt = cfg.timestep

    # The tetrahedral mesh is the hidden physics model.  Only the smooth,
    # photo-matched visual skin below is shown in the viewer.
    root_node.addObject(
        "VisualStyle",
        displayFlags=(
            "showVisualModels hideBehaviorModels hideCollisionModels "
            "hideMappings hideForceFields hideInteractionForceFields"
        ),
    )
    root_node.addObject("BackgroundSetting", color=[0.08, 0.10, 0.14, 1.0])

    # ── Camera ────────────────────────────────────────────────────────────
    root_node.addObject(
        "InteractiveCamera",
        name="camera",
        # Three-quarter side view with world -Z fixed as screen-up.  The arm's
        # local +Z points away from the plywood, so this places the mount at
        # the top of the image and the free end directly below it.
        position=[0.31, -0.42, 0.11],
        orientation=[-0.22103502, 0.67167218, -0.67167218, 0.22103502],
        distance=0.52201533,
        zNear=0.001,
        zFar=10.0,
    )

    # ── Solver stack (constraint-based) ───────────────────────────────────
    # Note: GenericConstraintSolver was replaced in SOFA v25.12.
    # BlockGaussSeidelConstraintSolver is the direct equivalent for the
    # default ProjectedGaussSeidel method.
    root_node.addObject("FreeMotionAnimationLoop")
    root_node.addObject(
        "BlockGaussSeidelConstraintSolver",
        tolerance=cfg.constraint_solver_tolerance,
        maxIterations=cfg.constraint_solver_max_iter,
    )

    # ── Arm node ──────────────────────────────────────────────────────────
    arm = root_node.addChild("Arm")

    # ODE + linear solver
    arm.addObject(
        "EulerImplicitSolver",
        name="odesolver",
        rayleighStiffness=cfg.ode_solver_rayleigh_stiffness,
        rayleighMass=cfg.ode_solver_rayleigh_mass,
    )
    arm.addObject("SparseLDLSolver", name="directSolver", template="CompressedRowSparseMatrixMat3x3d")

    # ── Mesh ──────────────────────────────────────────────────────────────
    mesh_path = Path(__file__).parent / cfg.mesh_file
    arm.addObject(
        "MeshGmshLoader",
        name="meshLoader",
        filename=str(mesh_path),
        scale3d=[1, 1, 1],
    )
    arm.addObject(
        "TetrahedronSetTopologyContainer",
        name="topo",
        src="@meshLoader",
    )
    arm.addObject("TetrahedronSetGeometryAlgorithms")

    # ── Degrees of freedom ────────────────────────────────────────────────
    arm.addObject(
        "MechanicalObject",
        name="dofs",
        template="Vec3d",
        src="@meshLoader",
    )

    # ── Mass ──────────────────────────────────────────────────────────
    # Arm-only mass; the external marker-frame mass is concentrated at the tip.
    # UniformMass distributes this evenly across all nodes.
    arm.addObject(
        "UniformMass",
        totalMass=cfg.arm_mass,
    )

    # ── FEM force field ───────────────────────────────────────────────────
    # co-rotational TetrahedronFEM handles large bending displacements.
    # youngModulus in Pa, poissonRatio dimensionless.
    arm.addObject(
        "TetrahedronFEMForceField",
        name="fem",
        template="Vec3d",
        youngModulus=cfg.young_modulus,
        poissonRatio=cfg.poisson_ratio,
        method="large",            # co-rotational formulation
        computeGlobalMatrix=False, # faster for large meshes
    )

    # ── Constraint correction (required by FreeMotionAnimationLoop) ───────
    # Note: 'solverName' was renamed to 'ODESolver' in SOFA v26.
    arm.addObject("LinearSolverConstraintCorrection", ODESolver="@odesolver")

    # ── Fixed boundary: base face (mount plate) ───────────────────────────
    # Wide box to robustly capture all base nodes (mesh Z starts at 0).
    arm.addObject(
        "BoxROI",
        name="baseROI",
        box=[-0.06, -0.06, -0.01,
              0.06,  0.06,  0.01],
        drawBoxes=False,
    )
    arm.addObject(
        "FixedProjectiveConstraint",
        name="fixedBase",
        indices="@baseROI.indices",
    )

    # ── Pneumatic pouches: 4 columns × 5 levels = 20 independent actuators ──
    # This matches the MuJoCo architecture: n_cols=4, n_pouches=5.
    # cavity_nodes[col][level] → (pouch_node, SurfacePressureConstraint)
    col_labels = ["East", "North", "West", "South"]
    cavity_nodes: list[list] = [[] for _ in range(cfg.n_cols)]
    pouch_tags = {
        cfg.pouch_cavity_tag(col, lvl)
        for col in range(cfg.n_cols)
        for lvl in range(cfg.n_levels)
    }
    pouch_surfaces = _load_pouch_surfaces(mesh_path, pouch_tags)

    for col in range(cfg.n_cols):
        for lvl in range(cfg.n_levels):
            tag = cfg.pouch_cavity_tag(col, lvl)
            node_name = f"Col{col}_{col_labels[col]}_Lvl{lvl}"
            pouch_node = arm.addChild(node_name)
            positions, triangles = pouch_surfaces[tag]

            pouch_node.addObject(
                "MeshTopology",
                name="pouchTopo",
                position=positions,
                triangles=triangles,
            )
            pouch_node.addObject(
                "MechanicalObject",
                name="pouchDofs",
                template="Vec3d",
                position=positions,
            )
            actuator = pouch_node.addObject(
                "SurfacePressureConstraint",
                name=f"pressure_c{col}_l{lvl}",
                template="Vec3d",
                value=0.0,
                triangles="@pouchTopo.triangles",
                valueType="pressure",
                # TPU-coated fabric is strain-limiting.  Without this physical
                # bound, an isotropic continuum cavity can inflate indefinitely
                # and eventually invert the surrounding tetrahedra.
                maxVolumeGrowth=(
                    cfg.pouch_initial_volume
                    * cfg.max_pouch_volume_growth_ratio
                ),
            )
            pouch_node.addObject(
                "BarycentricMapping",
                name="mapping",
                input="@../dofs",
                output="@pouchDofs",
                mapForces=False,
                mapMasses=False,
            )
            cavity_nodes[col].append((pouch_node, actuator))

    # ── Interactive pressure panel ────────────────────────────────────────
    # SofaImGui renders a Python Controller's custom Data fields in its
    # Components panel.  Keeping this controller out of SoftArmSim prevents
    # two pressure sources from competing in programmatic/headless runs.
    if enable_pressure_panel:
        from pressure_control import PressureControlPanel

        controls = root_node.addChild("PressureControls")
        controls.addObject(
            PressureControlPanel(
                cavity_nodes,
                cfg,
                name="PressureControlPanel",
                listening=True,
            )
        )


    # ── Tip tracking ──────────────────────────────────────────────────────
    # Match MuJoCo's sensor location at the centre of the external marker
    # frame, 12 mm beyond the arm's free face.
    tip_node = arm.addChild("Tip")
    tip_node.addObject(
        "MechanicalObject",
        name="tipDofs",
        template="Vec3d",
        position=[[0.0, 0.0, cfg.arm_length + cfg.tip_offset]],
    )
    tip_node.addObject(
        "UniformMass",
        name="endEffectorMass",
        totalMass=cfg.tip_mass,
    )
    tip_node.addObject(
        "BarycentricMapping",
        input="@../dofs",
        output="@tipDofs",
        mapForces=True,
        mapMasses=True,
    )

    # ── Photo-matched visual model ───────────────────────────────────────
    # 20 black pillow pouches, blue fabric carriers, separator plates, the
    # OptiTrack marker cross, and the fixed mounting plate.  All moving parts
    # are mapped to the FEM DOFs and therefore follow bending/extension.
    add_robot_visual(root_node, arm, cfg)

    return arm, cavity_nodes, tip_node
