"""
soft_arm_scene.py — SOFA + SoftRobots scene for the fabric pneumatic soft arm.

This file defines a SofaPython3-compatible scene builder function `createScene()`
that SOFA calls on startup.  It can also be used programmatically via
`SoftArmSim` in soft_arm_sim.py.

Physics overview
----------------
The arm body is modelled as a nearly-incompressible hyperelastic solid using
the Finite Element Method (FEM) on a tetrahedral mesh generated by Gmsh
(mesh/generate_mesh.py).

    Body mechanics
        TetrahedronFEMForceField (co-rotational, large deformation)
        Rayleigh damping (α on mass, β on stiffness)

    Pneumatic actuation
        SurfacePressureConstraint × 4 (one per column cavity)
        First-order pressure lag applied externally in soft_arm_sim.py

    Boundary conditions
        FixedConstraint on the base face (mesh tag 2 = mount plate)

    Solver stack (constraint-based)
        FreeMotionAnimationLoop
        GenericConstraintSolver
        SparseLDLSolver  (direct, robust for ~10k DOF problems)
        EulerImplicitSolver (with Rayleigh damping)

Scene graph
-----------
Root
 ├─ RequiredPlugin (SoftRobots, SofaPython3, SofaBaseLinearSolver, …)
 ├─ AnimationLoop (FreeMotionAnimationLoop)
 ├─ ConstraintSolver (GenericConstraintSolver)
 └─ Arm  (Node)
     ├─ EulerImplicitSolver
     ├─ SparseLDLSolver
     ├─ MeshGmshLoader          ← loads soft_arm.msh
     ├─ TetrahedronSetTopologyContainer
     ├─ MechanicalObject        ← DOFs (node positions)
     ├─ TetrahedronFEMForceField
     ├─ UniformMass
     ├─ LinearSolverConstraintCorrection
     ├─ FixedConstraint         ← base nodes (mount plate)
     ├─ Col0 / Col1 / Col2 / Col3  (sub-nodes for cavities)
     │   ├─ MeshTopology (surface triangles of cavity from BoxROI/TagFilter)
     │   └─ SurfacePressureConstraint
     └─ Tip  (sub-node)
         ├─ MechanicalObject    ← mapped tip position
         └─ BarycentricMapping  ← maps tip DOF to arm FEM DOFs
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Optional

# arm_config is always importable (pure Python, no SOFA dependency)
from arm_config import ArmConfig


# ---------------------------------------------------------------------------
# Scene creation entry point — called by SOFA on startup
# ---------------------------------------------------------------------------

def createScene(root_node, cfg: Optional[ArmConfig] = None):
    """Build the SOFA scene graph for the soft arm.

    Parameters
    ----------
    root_node : Sofa.Core.Node
        The SOFA root node (provided automatically by `runSofa` or by
        `Sofa.Simulation.init()`).
    cfg : ArmConfig, optional
        Physical parameters.  Defaults to ``ArmConfig()``.

    Returns
    -------
    arm_node : Sofa.Core.Node
        The arm sub-node; use it to access DOFs, actuators, and sensors
        from outside the scene.
    """
    if cfg is None:
        cfg = ArmConfig()

    # ── Required plugins ──────────────────────────────────────────────────
    root_node.addObject("RequiredPlugin", pluginName=[
        "SoftRobots",
        "SofaPython3",
        "SofaBaseLinearSolver",
        "SofaConstraint",
        "SofaImplicitOdeSolver",
        "SofaMeshCollision",
        "SofaOpenglVisual",
        "SofaGeneralSimpleFem",
        "SofaTopologyMapping",
        "SofaLoader",
        "SofaBoundaryCondition",
    ])

    # ── Global scene settings ─────────────────────────────────────────────
    root_node.gravity = [0.0, 0.0, -9.81]   # standard gravity; arm hangs -Z
    root_node.dt = cfg.timestep

    root_node.addObject("VisualStyle", displayFlags="showBehaviorModels showForceFields")
    root_node.addObject("BackgroundSetting", color=[0.08, 0.10, 0.14, 1.0])

    # ── Solver stack (constraint-based) ───────────────────────────────────
    root_node.addObject("FreeMotionAnimationLoop")
    root_node.addObject(
        "GenericConstraintSolver",
        tolerance=cfg.constraint_solver_tolerance,
        maxIterations=cfg.constraint_solver_max_iter,
    )

    # ── Arm node ──────────────────────────────────────────────────────────
    arm = root_node.addChild("Arm")

    # ODE + linear solver
    arm.addObject(
        "EulerImplicitSolver",
        name="odesolver",
        rayleighStiffness=cfg.ode_solver_rayleigh_stiffness,
        rayleighMass=cfg.ode_solver_rayleigh_mass,
    )
    arm.addObject("SparseLDLSolver", name="directSolver", template="CompressedRowSparseMatrixMat3x3d")

    # ── Mesh ──────────────────────────────────────────────────────────────
    mesh_path = Path(__file__).parent / cfg.mesh_file
    arm.addObject(
        "MeshGmshLoader",
        name="meshLoader",
        filename=str(mesh_path),
        scale3d=[1, 1, 1],
    )
    arm.addObject(
        "TetrahedronSetTopologyContainer",
        name="topo",
        src="@meshLoader",
    )
    arm.addObject("TetrahedronSetGeometryAlgorithms")

    # ── Degrees of freedom ────────────────────────────────────────────────
    arm.addObject(
        "MechanicalObject",
        name="dofs",
        template="Vec3d",
        src="@meshLoader",
    )

    # ── Mass ──────────────────────────────────────────────────────────────
    arm.addObject(
        "UniformMass",
        totalMass=cfg.density,   # SOFA will distribute over mesh volume
    )

    # ── FEM force field ───────────────────────────────────────────────────
    # co-rotational TetrahedronFEM handles large bending displacements.
    # youngModulus in Pa, poissonRatio dimensionless.
    arm.addObject(
        "TetrahedronFEMForceField",
        name="fem",
        template="Vec3d",
        youngModulus=cfg.young_modulus,
        poissonRatio=cfg.poisson_ratio,
        method="large",            # co-rotational formulation
        computeGlobalMatrix=False, # faster for large meshes
    )

    # ── Constraint correction (required by FreeMotionAnimationLoop) ───────
    arm.addObject("LinearSolverConstraintCorrection", solverName="@directSolver")

    # ── Fixed boundary: base face (mount plate) ───────────────────────────
    arm.addObject(
        "BoxROI",
        name="baseROI",
        # A thin slab at Z ≈ 0 (base of the arm)
        box=[-0.06, -0.06, -0.005,
              0.06,  0.06,  0.005],
        drawBoxes=True,
    )
    arm.addObject(
        "FixedConstraint",
        name="fixedBase",
        indices="@baseROI.indices",
    )

    # ── Pneumatic column cavities ─────────────────────────────────────────
    col_labels  = ["East", "North", "West", "South"]
    col_colors  = [
        [0.92, 0.55, 0.08, 1.0],   # col 0 East  : orange
        [0.10, 0.68, 0.18, 1.0],   # col 1 North : green
        [0.82, 0.18, 0.08, 1.0],   # col 2 West  : red
        [0.08, 0.28, 0.90, 1.0],   # col 3 South : blue
    ]

    cavity_nodes = []
    for i in range(cfg.n_cols):
        phi_deg = cfg.col_azimuths_deg()[i]
        phi     = math.radians(phi_deg)
        cx      = cfg.col_offset * math.cos(phi)
        cy      = cfg.col_offset * math.sin(phi)
        tag     = cfg.col_cavity_tags()[i]

        col_node = arm.addChild(f"Col{i}_{col_labels[i]}")

        # Surface topology of this cavity (loaded from physical group tag)
        col_node.addObject(
            "MeshGmshLoader",
            name="cavityLoader",
            filename=str(mesh_path),
            # Load only the triangles belonging to the cavity surface group
        )
        col_node.addObject(
            "MeshTopology",
            name="cavityTopo",
            src="@cavityLoader",
        )
        col_node.addObject(
            "MechanicalObject",
            name="cavityDofs",
            template="Vec3d",
        )
        col_node.addObject(
            "BarycentricMapping",
            mapForces=False,
            mapMasses=False,
        )

        # Pressure actuator — pressure value is set each timestep by the wrapper
        actuator = col_node.addObject(
            "SurfacePressureConstraint",
            name=f"pressure{i}",
            template="Vec3d",
            value=0.0,           # Pa; will be updated by soft_arm_sim.py
            triangles="@cavityTopo.triangles",
            valueType="pressure",  # as opposed to volume
        )
        cavity_nodes.append((col_node, actuator))

    # ── Tip tracking ──────────────────────────────────────────────────────
    # Map a virtual "tip" node to the centroid of the bottom face.
    tip_node = arm.addChild("Tip")
    tip_node.addObject(
        "MechanicalObject",
        name="tipDofs",
        template="Vec3d",
        position=[[0.0, 0.0, cfg.arm_length]],  # initial tip position
    )
    tip_node.addObject(
        "BarycentricMapping",
        input="@../dofs",
        output="@tipDofs",
    )

    return arm, cavity_nodes, tip_node
